const portfolio = {
  name: "Aman Sharma",
  title: "Blockchain & Full Stack Engineer",
  bio: "Building on-chain apps that scale.",
  github: "https://github.com/AmanSharma7799",
  X: "https://x.com/amansharma7799",
  projects: [
    {
      name: "Universal Ledger (Google Cloud)",
      link: "https://universal-ledger-frontend.vercel.app",
      desc: "A simplified, blockchain-inspired tamper-evident ledger system, modeled after Google Cloud Universal Ledger. This backend application allows you to append entries, verify integrity, and audit logs using SHA256-based hash chaining — without needing a full blockchain.",
      platform: "vercel",
    },
    {
      name: "DEX (Decentralized Exchange)",
      link: "https://github.com/AmanSharma7799/dex",
      desc: "This project implements a Decentralized Exchange (DEX) built using Forge for smart contract development and RabbitMQ for event handling.",
      platform: "github",
    },
    {
      name: "Flashloan Cross-Exchange",
      link: "https://github.com/AmanSharma7799/flashloan-cross-exchange",
      desc: "Arbitrage bot using flash loans across DEXs(Uniswap & SushiSwap). It leverages FlashSwaps on Uniswap to borrow tokens and executes cross-exchange trades to capture arbitrage profits between the two liquidity pools.",
      platform: "github",
    },
    {
      name: "NFT Minting",
      link: "https://nft-minting-bay.vercel.app",
      desc: "NFT Minting Decentralized Application (DApp) built with React and Ethers.js v6. It connects to the already deployed ERC-721 smart contract on the Sepolia testnet, allowing users to mint NFTs by providing a metadata URL.",
      platform: "vercel",
    },
    {
      name: "zkProof-of-Square",
      link: "https://github.com/AmanSharma7799/zk-proof-impl",
      desc: "This ZK circuit is written in Circom and uses Groth16 via SnarkJS to generate and verify zk-SNARK proofs. It showcases the core principles behind private computation, identity proofs, and trustless verification in Web3 and cryptography systems.",
      platform: "github",
    },
    {
      name: "Zer0Curve",
      link: "https://github.com/AmanSharma7799/curve-dex",
      desc: "A Curve-inspired DEX PoC focused on efficient stablecoin swaps with custom AMM logic. Also, it has StableSwap Pools, veCRV (voting escrow) & Governance system, among other features.",
      platform: "github",
    },
    {
      name: "Merkle Tree Verifier",
      link: "https://github.com/AmanSharma7799/merkle-tree",
      desc: "A simple and gas-efficient smart contract for verifying Merkle proofs on-chain using OpenZeppelin's MerkleProof library. This is useful for implementing whitelists, airdrops, and secure inclusion proofs.",
      platform: "github",
    },
    {
      name: "BouncyCastle RSA",
      link: "https://github.com/AmanSharma7799/bouncy-castle-rsa",
      desc: "This project demonstrates how to use the Bouncy Castle cryptographic library to perform RSA encryption and decryption in Java.",
      platform: "github",
    },
    {
      name: "IntentSwap",
      link: "https://github.com/AmanSharma7799/intent-swap",
      desc: "IntentSwap is a simplified proof-of-concept implementation of an intent-based token swapping protocol in Solidity. Instead of placing rigid on-chain orders, users sign flexible off-chain intents, which are later fulfilled by solvers through optimal routing or coincidence of wants (CoW) .",
      platform: "github",
    },
    {
      name: "MetaAuth",
      link: "https://github.com/AmanSharma7799/authentication-with-metamask",
      desc: "A way to integrate the use of blockchain for Authentication. This is a blockchain-enabled authentication project developed using NextJS, which allows user to sign up and login using Metamask.",
      platform: "github",
    },
  ],
  skills: [
    "Solidity",
    "Foundry",
    "Hardhat",
    "Java",
    "Springboot",
    "Hibernate",
    "Javascript",
    "React.js",
    "Node.js",
    "Express.js",
    "Next.js",
    "AWS",
    "Azure Devops",
    "Dockers",
    "MySQL",
    "MongoDB",
    "GitHub Actions",
  ],
  contact: "+91 8856044490",
  email: "aman02468@gmail.com",
  experience: [
    {
      company: "Deloitte",
      title: "Consultant",
      duration: "September 2023 – Present",
      logo: "assets/Deloitte-Emblem.png",
      responsibilities: [
        " Engineered contracts to efficiently manage liquidity pools for decentralized exchanges (DEXs), boosting capital efficiency by 20%",
        " Designed and deployed robust Solidity contracts to handle token swaps on decentralized exchanges, increasing transaction volume by 25%",
        " Built cross-chain interoperability into smart contracts, facilitating seamless blockchain network interactions",
        " Developed complex algorithms for smart contracts, successfully reducing gas fees by 15% while maintaining functionality",
      ],
    },
    {
      company: "Stepstrong Software",
      title: "Senior Software Engineer",
      duration: "April 2020 – August 2023",
      logo: "assets/stepstrong.png",
      responsibilities: [
        " Developed Solidity-based solutions to track and verify the ownership of non-fungible tokens (NFTs), ensuring 99.9% accurate tracking.",
        " Integrated smart contracts with Hardware Wallets, strengthening transactions security & reducing fraud risk by 35%.",
        " Architected decentralized loan contracts, Processing over $2M in secure peer-to-peer lending with zero security breaches.",
        " Integrated CI/CD pipelines using GitHub Actions and Docker",
        " Implemented Scalable Microservices Using SpringBoot, improving System Uptime by 35% for an Insurance Platform.",
      ],
    },
  ],
};
